// connect motor controller pins to Arduino digital pins
// motor one
int enA = 5;
int in1 = 6;
int in2 = 7;
// motor two
int enB = 10;
int in3 = 9;
int in4 = 8;
int moveSpeed=150;

int ardublockUltrasonicSensorCodeAutoGeneratedReturnCM(int trigPin, int echoPin)
{
  int duration;
  pinMode(trigPin, OUTPUT);
  pinMode(echoPin, INPUT);
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(20);
  digitalWrite(trigPin, LOW);
  duration = pulseIn(echoPin, HIGH);
  duration = duration / 59;
  return duration;
}

int _ABVAR_1_ss;

void setup()
{
_ABVAR_1_ss = 0;

Serial.begin(9600);

// set all the motor control pins to outputs
  pinMode(enA, OUTPUT);
  pinMode(enB, OUTPUT);
  pinMode(in1, OUTPUT);
  pinMode(in2, OUTPUT);
  pinMode(in3, OUTPUT);
  pinMode(in4, OUTPUT);

}

void testMotor() {
  void moveleftMotorForward();
  void moveleftMotorBackward();
  void moverightMotorForward();
  void moverightMotorBackward();
  void breakLeftMotor();
  void breakRightMotor();
  void turn45Left();
  void turn45Right();
  void moveForward();
  void moveBackward();
  void breakAll();
}

 void moveleftMotorForward(){
  digitalWrite(in1, HIGH);
  digitalWrite(in2, LOW);
  analogWrite(enA, moveSpeed);
  Serial.println("left motor forward");
  }
 void moveleftMotorBackward(){
  digitalWrite(in2, HIGH);
  digitalWrite(in1, LOW);
  analogWrite(enA, moveSpeed);
  Serial.println("left motor backward");}
 void moverightMotorForward(){
  digitalWrite(in4, HIGH);
  digitalWrite(in3, LOW);
  analogWrite(enB, moveSpeed);
  Serial.println("right motor forward");
  }
 void moverightMotorBackward(){
  digitalWrite(in3, HIGH);
  digitalWrite(in4, LOW);
  analogWrite(enB, moveSpeed);
  Serial.println("right motor backward");}
 void breakLeftMotor(){digitalWrite(in2, LOW);
  digitalWrite(in1, LOW);
  analogWrite(enA, LOW);
  Serial.println("break left motor ");}
 void breakRightMotor(){
  digitalWrite(in3, LOW);
  digitalWrite(in2, LOW);
  analogWrite(enB, LOW);
  Serial.println("break motor backward");
  }
 void turn45Left(){moveleftMotorBackward();moverightMotorForward();moveleftMotorBackward();moverightMotorForward();}
 void turn45Right(){}
 void moveForward(){moverightMotorForward();moveleftMotorForward();}
 void moveBackward(){moverightMotorBackward();moveleftMotorBackward();}
 void breakAll() {breakLeftMotor();breakRightMotor();}


void loop()
{
_ABVAR_1_ss = ardublockUltrasonicSensorCodeAutoGeneratedReturnCM( 2 , 3 ) ;
Serial.print( _ABVAR_1_ss );
Serial.println("");
//moveleftMotorForward();
//delay(500);
if(_ABVAR_1_ss>15) {
Serial.print( _ABVAR_1_ss );
Serial.println("moving");
moveForward();
}
else
{
  turn45Left();
  turn45Left();
}




}


